name: Restore only
on:
  # push:
  workflow_dispatch:

jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        shell: bash
        id: date
        run: echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v2
      - uses: actions/cache/restore@700-actionscache-granular-cache-control
        id: cache-restore
        with:
          path: ${{ github.workspace }}/node_modules
          key: key-not-present
          restore-keys: restore-key-not-present
      - name: NPM install
        shell: bash
        if: steps.cache-restore.outputs.cache-hit != 'true'
        run: |
          pwd
          npm install
          echo "${{ steps.date.output }}"
