name: Save only
on:
  # push:
  workflow_dispatch:
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: NPM install
        shell: bash
        run: |
          pwd
          npm install
      - uses: actions/cache/save@kotewar/save-warnings
        id: cache-save
        with:
          path: ${{ github.workspace }}/node_modules
          key: 2
