name: Check if cache exists for a given key
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check key
        id: key
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          BRANCH=${{ github.ref }}
          KEY= "cache"
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH --key $KEY | cut -f 1 )
          
          echo "Checking if key exists"
          echo $cacheKeysForPR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
