name: Check if cache exists for a given key
on:
  # push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Check key
        id: key
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          BRANCH=${{ github.ref }}
          KEY='cache'
          
          echo "Fetching list of cache key"
          cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH --key $KEY | cut -f 1 )
          
          echo "Checking if key exists"
          
          for cacheKey in $cacheKeysForPR
          do
              if [ $cacheKey == $KEY ]
              then
                echo "KEY_FOUND=true" >> $GITHUB_OUTPUT
                echo "KEY FOUND"
                break
              fi
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Condition
        id: check
        if: ${{steps.key.outputs.KEY_FOUND == 'true' }}
        run: |
          echo "Key found :D"
        
